# Use root/example as user/password credentials
# run with docker-compose -f mariadb.yml up --no-start


version: '3.1'

services:

  db:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080

